### ISSUE TITLE
Chrome displays fine but Safari doesn't

### ISSUE THREAD

**Issue by sky7st** [AnyChart/AnyChart#103]
I'm using stock chart for my project.
But there's a issue.

The chart shows correctly on chrome but safari doesn't.
It seems like the data doesn't load correctly to the chart drawing in safari 
because the Y axis labels are shown correctly which is setted by my custom tick array.
But the legend didn't show correctly.

This is the chart in chrome looks like(work):
![work](https://user-images.githubusercontent.com/25301882/65240754-90ff7380-db14-11e9-90ad-a2ed7c250519.png)

and this is the chart in safari:

![not work](https://user-images.githubusercontent.com/25301882/65240684-6f05f100-db14-11e9-8fa2-1e1c89201c21.png)

**Comment by Shestac92** [comment]
@sky7st 
With the high probability, the issue comes from the specific default dateTime format of the Safari browser, which differs from Chrome or FF.
You handle it very easy, you can apply the default dateTime format pattern manually. 
For example, date-time values in your data are the following `2019-09-20 22:37:00`. In this case, you can add the following line in the beginning of your chart configuration code:
```
anychart.format.inputDateTimeFormat('yyyy-MM-dd HH:mm:ss');
```
This will solve the issue for Safari browser. Please, let me know if it doesn't work and provide one row of your data to prepare a proper dateTime pattern.

**Comment by sky7st** [comment]
Thanks for your help.
It works fine on Safari now.
