### ISSUE TITLE
Applying rounded corners to Progress with 0 value in Gantt chart shows a concave progress bar

### ISSUE THREAD

**Issue by threeFatCat** [AnyChart/AnyChart#121]
I followed this tutorial [here](https://playground.anychart.com/docs/v8/samples/GANTT_Custom_Drawing_01). But this sample doesn't have modifications for progress bars, so I used the method progress() to access progress bars and added this:

`tasks.progress().rendering().drawer(drawingFunction)`

I noticed that if I apply the rounded corners, to data with **zero** `progressValue`, it shows the progress bars with **concave** corners, which progress should not be visible at all or at least convex corners

![bug](https://user-images.githubusercontent.com/11312281/76062242-47bab780-5fc0-11ea-8a3d-15ae5edf3f73.PNG)

**Question**: How do I get the value of the `progressValue` inside the `drawingFunction` ? So I can validate it and apply the rounded corners only to with **non-zero** value? or is there any way to fix the concave corners?

I also posted question in [Stackoverflow](https://stackoverflow.com/questions/60559283/how-to-access-data-passed-within-a-function-in-anychartjs).

**Comment by Shestac92** [comment]
@threeFatCat 
In the `drawingFunction()` you can get the required value like this:
```
this.tag.item.get('progressValue')
```
For details, check the [modified sample](https://playground.anychart.com/N8qLXSsr).

There's no bug with the drawing function. You get the bars with concave corners because the bar width is less than 2x corner radius. You have to reduce the radius or somehow handle the situation when the progress value is quite small.
