### ISSUE TITLE
Using custom font in Tag Cloud

### ISSUE THREAD

**Issue by ggmartins** [AnyChart/AnyChart#140]
Hi AnyChart team,

first, I have to say this is a great piece of work, I'm really happy learning anycharts. Congrats!

I'm struggling a little trying to get the tag cloud to work with a custom font. Not sure the custom font is loading in time for where tagCloud calculate the word size. I can only get it to work after forcing the reload of the page:

```
  <head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <title>Stock Streamer</title>
  <link href="https://fonts.googleapis.com/css?family=Notable" rel="stylesheet"> 
  <meta content="Trending Stocks" name="keywords">
  <script src="https://cdn.anychart.com/releases/8.7.1/js/anychart-core.min.js"></script>
  <script src="https://cdn.anychart.com/releases/8.7.1/js/anychart-tag-cloud.min.js"></script>
 ...
 <body>
 <script type="text/javascript">
  var chart
  anychart.onDocumentReady(function () {
  chart = anychart.tagCloud()
  chart.background({fill: "#2F2F2F 3.5"})
  chart.hovered({fill: "#0000FF 3.5"})
  chart.selected({fill: "#0000FF 3.5"})
  chart.palette(palette);
  chart.fontFamily('Notable');
  chart.data(data)
...
  chart.container("container")
  chart.draw();
  //setInterval(function(){ window.location.reload() }, 3000);
``` 

![image](https://user-images.githubusercontent.com/2147779/85234163-18924f80-b3d1-11ea-98f6-3ce74c801f62.png)
with window.location.reload() or resizing in the dev console: 
![image](https://user-images.githubusercontent.com/2147779/85234202-5b542780-b3d1-11ea-97c4-32c7cc00e954.png)

Please let me know if there's any thing I can do to fix it, Thanks!, G.

**Comment by Shestac92** [comment]
@ggmartins 
It happens because the chart calculates words bounds before the font is loaded (if the font is not cached). Then it simply applies the font to the chart but bounds remain the same.
To avoid it, you can use FontFaceSet interface provided by the browser to wait until the font is loaded and only after that draw the chart. It guarantees that chart will be created with the target font and it doesn't block the page.
For details, check [the sample](https://playground.anychart.com/b1sGMkKo/0).

**Comment by ggmartins** [comment]
easy fix, thanks!
