### ISSUE TITLE
How to change the color of an specific candlestick on a candlestick chart?

### ISSUE THREAD

**Issue by cleyversoncosta** [AnyChart/AnyChart#174]
How to change the color of an specific candlestick on a candlestick chart?

**Comment by Shestac92** [comment]
@cleyversoncosta 
To achieve that you should execute the following steps:
1) apply the true flag to the Stock chart constructor to enable individual point settings
2) add the desired color to the particular point in the data
3) map this field as risingFill or fallingFill (or both to ignore the point direction)

For details, check [the sample](https://playground.anychart.com/e4cGdD4G/0).

**Comment by saikiranvadhi** [comment]
@Shestac92, this is great, almost exactly what I'm looking for. 
There is one additional ask here, is there a way to pass the transparency parameter similar to the second argument we pass here `series.normal().fallingFill("#00cc99", 0.3);` through the data, so that it is applied only to a specific candle?
