### ISSUE TITLE
Scroll for gantt chart

### ISSUE THREAD

**Issue by KL3YB3R** [AnyChart/AnyChart#206]
Good night.

I have a problem with the gantt chart when the date data exceeds a period of at least one year, the cells of the timeline are placed small, making the days of the month not visible. I have tried to put the Scroller code that is in common configurations, but it does not work for me. Could you help me? Thank you

**Comment by sturdystablestalwart** [comment]
@KL3YB3R 
It seems that the solution to your issue is using [Zooming](https://docs.anychart.com/Gantt_Chart/Basic_Settings#zooming). 
Alternatively, it may be more useful for you to find and delete the `chart.fitAll();` line. It's also beneficial to read more on [Fitting to Width](https://docs.anychart.com/Gantt_Chart/Basic_Settings#fitting_to_width).

If you have any additional questions, please provide the following items, so I can assist you better:
1. [Playground demo](https://playground.anychart.com/) / HTML, CSS, and JS code 
2. Data sample
