### ISSUE TITLE
When we use zoomTo(startdate,enddate) in gantt chart it uses (month-1) in start and end dates

### ISSUE THREAD

**Issue by NightKaos** [AnyChart/AnyChart#31]
In https://playground.anychart.com/docs/8.1.0/samples/GANTT_Chart_10
If we replace the chart.fitAll(); by chart.zoomTo(Date.UTC(2013,5,1), Date.UTC(2013,6,31));
Will show June and July instead of May and June.

**Comment by loki20beta** [comment]
@NightKaos Date.UTC month parameter starts from 0, not 1, this is how it works in JavaScript:
https://docs.microsoft.com/en-us/scripting/javascript/reference/date-utc-function-javascript
month - Required. The month as an integer between 0 and 11 (January to December).

So, this is an expected behavior, if you take a look at periods - they all behave like that too.

**Comment by NightKaos** [comment]
@loki20beta Thank you very much for your reply! Yes indeed... my mistake!

**Comment by loki20beta** [comment]
@NightKaos no problem, you are welcome.
