### ISSUE TITLE
v8.2.0 - compile error DataGridButton anychart.core.ui

### ISSUE THREAD

**Issue by ImranAhmed** [AnyChart/AnyChart#37]
I've just upgraded to v8.2.0 from v8.1.0 and I am seeing this compile error.

ERROR in node_modules/anychart/dist/index.d.ts(30337,55): error TS2694: Namespace 'anychart.core.ui' has no exported member 'DataGridButton'.

**Comment by loki20beta** [comment]
@ImranAhmed we will check and get back to you

**Comment by Shestac92** [comment]
@ImranAhmed 
unfortunately, the fixed Typedefs will be released with the next minor update (during next two weeks). Exactly this issue is already known and will be fixed too. I will update you when the release becomes available. Until that, we recommend you to use dev-preview version or downgrade to 8.1.0 version.

**Comment by Shestac92** [comment]
@ImranAhmed 
Our team has prepared a dev-preview of 8.2.1 update and you can try it in your projects. This update includes many bug fixes of index.d.ts.
To get this update replace in ‘package.json’ the current AnyChart dependence with the following  "anychart": "8.2.1-rc.0"
Or you can download it manually via NPM: $ npm install anychart@8.2.1-rc.0	
Very soon our team will provide public release of 8.2.1 update.

**Comment by ImranAhmed** [comment]
I can confirm that this is fixed in v8.2.1, thanks.
