### ISSUE TITLE
very small number values

### ISSUE THREAD

**Issue by omazapa** [AnyChart/AnyChart#42]
Dear Anychart support
I am having the next issue (with anystock)
https://stackoverflow.com/questions/48918872/very-small-number-values-in-anychart-cause-graph-to-crash-oom

some news? 

in anychart 8.0.1 and 8.0.0 it works but in the newest versions it donts.
I try 
anychart.format.locales.default.numberLocale.decimalsCount = 16;
anychart.format.locales.default.numberLocale.scale = true

or passing the number in  scientific notation 
var num = 0.0000000000556789;
var n = num.toExponential();

but it dont works.
some temporal solution?

thanks for your help.

Best Reagards,
Omar.

**Comment by Shestac92** [comment]
@omazapa 
In the latest version 8.2.1, small values shouldn't lead to page crush because of small values. Unfortunately, the yScale can't calculate very small ticks correctly. 
The problem reported on StackOverflow now is not reproduced - https://playground.anychart.com/rmstX3xn

As a temporary workaround, we can suggest truncating decimals from the data values. And then add decimals as a scientific notation for example in all labels. A sample of such approach you can find here - https://playground.anychart.com/TI8L6uLV/0

**Comment by omazapa** [comment]
Dear @Shestac92 
lets try this example with real data from exchange
https://drive.google.com/file/d/1h5Ij9I0rMIhQylxEWtikXF1jlmq36ynA/view?usp=sharing

in case that it can be loaded lets move the scroller. (produce Aw! Snap)

in the line 20 and 21 I have a line commented, scaling the data the system works.
Thanks

**Comment by Shestac92** [comment]
@omazapa 
thank you for this sample! I guess the problem comes from ticks calculation or the problem still exists. I will show this to our dev team. If any updates or fixes become available, I will notify you.
yes, scaling approach may solve it temporarily.

**Comment by omazapa** [comment]
Thank you @Shestac92
I am working with v8.0.1 for the moment, it that dont have that problem.

**Comment by jackvial** [comment]
Candlestick charts were breaking for values like 0.00002222 etc.. v8.0.1 fixes the issue for me.

**Comment by Shestac92** [comment]
@omazapa @jackvial 
We glad to notify you that the fix for your issue is available with the 8.3.0 version update. Please, update your AnyChart binaries to get the fix. You can download all required binaries using our CDN - https://www.anychart.com/download/cdn/?v=8.3.0
Now small data values will not freeze the browser page.

**Comment by davidmcooper** [comment]
This issue appears to have regressed in AnyChart versions newer than 8.3.0.  A sample playground example is available here:

https://playground.anychart.com/ZG0v32Ck/1

This renders successfully with AnyChart 8.3 but if you change the version to a newer AnyChart version such as 8.7.1 it crashes the browser tab completely.

**Comment by Shestac92** [comment]
@davidmcooper 
Thank you for the report! We will investigate this issue and back to you when we get results.

**Comment by Shestac92** [comment]
@davidmcooper 
Please, can you specify what is the project you are using the library for? This information is required to link the report to a client. You can contact us via support@anychart.com regarding that.

**Comment by davidmcooper** [comment]
This issue is still reproducible with AnyChart 8.9.0 with the playground link I'd provided:

https://playground.anychart.com/ZG0v32Ck/1

**Comment by Shestac92** [comment]
@davidmcooper 
We have just released v8.10.0 that includes fixes for the issue. Please, check and let us know if there are any issues left.

**Comment by davidmcooper** [comment]
Confirmed this resolves the issue. Thank you.
