### ISSUE TITLE
Mouse hover is not showing Point Details like Cross hair in anychart.charts.Cartesian;

### ISSUE THREAD

**Issue by SwardCoder** [AnyChart/AnyChart#86]
Hi i have a Cartesian Graph like i gave Date Time : HH:mm as column and some value as Row

so when graph displays it  is showing the exact mark HH:mm:ss of hovered region as tickValue in case of  Cross hair Format method 

like
```
   this.chart.crosshair().xLabel().format(function () {
            return anychart.format.dateTime(this.tickValue, 'HH:mm:ss');
        });
```
in the above code i am able to get tickValue on mouse hover of crosshair method

but when i was trying to get same tickValue using mouse Hover of Tool tip i am not getting 
so please suggest me how to get tickValue for Cartesian on mouse hover event when i am using method like 
```
this.chart.listen('rowMouseOver', (e: any) => {
            return `this.tickValue`; // this is not working and saying tickValue is undefined
        });
```

so please help me how to get tickValue for MouseHOver event

**Comment by imaximova** [comment]
@SwardCoder, the rowMouseOver() method works only for Gantt charts and cannot be used for cartesian ones. Can you please explain in detail what you're trying to achieve? If you want to format the tooltip, you'll have to write "this.x", not "this.tickValue". And the value won't change while moving the mouse because it's fixed for each point.
Learn more here: https://api.anychart.com/anychart.core.ui.Tooltip#titleFormat
https://api.anychart.com/anychart.core.ui.Tooltip#format

**Comment by SwardCoder** [comment]
ok thank you imaximova

**Comment by SwardCoder** [comment]
@imaximova  i tried with  this.chart.crosshair().xLabel().format instead and it worked 
thank you
