### ISSUE TITLE
Saved image cannot be opened

### ISSUE THREAD

**Issue by tr14466** [AnyChart/AnyChart#97]
Hi,
saved image cannot be opened?
![sss](https://user-images.githubusercontent.com/53610056/63750615-5b35e900-c8e0-11e9-8571-c18e2e86d6b9.png)
![ssss](https://user-images.githubusercontent.com/53610056/63750859-d4cdd700-c8e0-11e9-9674-e8ee7c72cf2b.png)

1.This is a saved picture.
![anychart](https://user-images.githubusercontent.com/53610056/63750906-e9aa6a80-c8e0-11e9-82c4-765a0dfa3908.png)

**Comment by Shestac92** [comment]
@tr14466 
In the 8.7.0 update, we implemented the client-side exporting feature which is default now. Unfortunately, due to a bug, it can bring this problem. We are going to fix it in the upcoming update.
As a temporary workaround, you can use the AnyChart export-server as before. To achieve that, just add the following code at the beginning of creating a chart:
```
  anychart.exports.clientside({
    enabled: false
  });
```

**Comment by tr14466** [comment]
> @tr14466
> In the 8.7.0 update, we implemented the client-side exporting feature which is default now. Unfortunately, due to a bug, it can bring this problem. We are going to fix it in the upcoming update.
> As a temporary workaround, you can use the AnyChart export-server as before. To achieve that, just add the following code at the beginning of creating a chart:
> 
> ```
>   anychart.exports.clientside({
>     enabled: false
>   });
> ```

That's fine. Thank you!

**Comment by Shestac92** [comment]
@tr14466 
We are glad to notify you that we have released 8.7.1 version update.
It includes the fix for the issue you reported.

Now the clientside exporting feature works properly as a default!
